apiVersion: v1
kind: Pod
metadata:
  name: fib-client-pod
  labels:
    component: web
spec:
  containers:
    - name: fib-client
      image: rgederin/fib-client-standalone-k8s
      ports:
        - containerPort: 3000
