apiVersion: v1
kind: Pod
metadata:
  name: overlimit-pod
spec:
  containers:
    - name: overlimit-pod-container
      image: nginx
      resources:
        limits:
          cpu: "800m"
        requests:
          cpu: "500m"
