apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{ if eq .Values.appVersion "v1" }}
  DATABASE_PORT: {{ .Values.v1DatabaseHost }}
  DATABASE_HOST: {{ .Values.v1DatabasePort }}
  {{ else if eq .Values.appVersion "v2" }}
  DATABASE_PORT: {{ .Values.v2DatabaseHost }}
  DATABASE_HOST: {{ .Values.v2DatabasePort }}
  {{ else }}
  DATABASE_PORT: {{ .Values.defaultDatabaseHost }}
  DATABASE_HOST: {{ .Values.defaultDatabasePort }}
  {{ end }}

