version: "3"
services:

  spring-boot-k8s-service:
    image: "rgederin/spring-boot-k8s-config:0.0.1-SNAPSHOT"
    ports:
      - 8080:8080
    environment:
      SECRETS_USERNAME: docker-compose-username
      SECRETS_PASSWORD: docker-compose-password
