apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: task2
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - wget spring-app-service:8080/api/secrets
          restartPolicy: OnFailure
