apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  labels:
    component: spring-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31515
  selector:
    component: spring-app
